### ISSUE TITLE
scrub time shortcut not changing with keymap I have

### ISSUE THREAD

**Issue by gakutada** [Pullusb/greasepencil-addon#19] opened 2022-04-17 19:23 UTC
Hi, I wish you could help me on this,
I am using this custom keymap here
https://drive.google.com/file/d/1bmRwuXaLUa51K_B2_gFK4jHf8QXsUQdM/view?usp=sharing

but I am mapping alt and MMB to other action and if I change time scrub to other mapping, it is still saves shift alt LMB as that action. 
Is there way to remap but not doing that action?

cheers
Gaku

**Comment by Pullusb** [comment] 2022-04-17 22:07
Hi Gaku !

> but I am mapping alt and MMB to other action and if I change time scrub to other mapping, it is still saves shift alt LMB as that action.
> Is there way to remap but not doing that action?

Not sure if I understand what you're trying to achieve... can you be more specific ?  
Explain precisely what you have currently and what you want in the end.

I see `alt + MMB` is doing a view Pan in your keymap so what key you want to use for timeline call ? (BTW personally I use `Alt + RMB`)

You say `shift + alt + LMB` does an action but what action exactly ? Calling timeline scrub ?

Did you try to change keymap directly in keymap editor or did you use the dedicated button in addon preferences ?

Samuel.

**Comment by gakutada** [comment] 2022-04-17 22:32
Hi Samuel.

Thank you!
and sorry it was not too clear, I changed mapping in GP addon inside of
preference for time scrub from Alt+MMB to Alt+Shift+Ctrl+MMD for example,
and it did change for that key but if I use alt+Shift+LMB which I mapped
for camera pan but it calls time scrub as well. so I cannot pan.

I guess you could try reading my keymap and change time scrub and see if
you don't see any time scrub with   alt+Shift+LMB ?

hope it makes sense.
thanks!
Gaku
  ____

 *VEDA* online ltd http://veda-online.com/  wellington NZ
http://gakutada.com/

**Comment by Pullusb** [comment] 2022-04-17 22:50
Ok, I get it now,
I will investigate tomorrow evening if I got time.
now night time in France ;) .


Totally unrelated, but I took a quick tour on your website from the link in your answer. What an Impressive art journey !

**Comment by gakutada** [comment] 2022-04-17 23:24
Sweet, that's awesome!!

Thank you so much, Samuel.
Grease Pencil is surely part of my journey:)
cheers
Gaku
  ____

 *VEDA* online ltd http://veda-online.com/  wellington NZ
http://gakutada.com/

**Comment by Pullusb** [comment] 2022-04-18 21:15
Hi,
So I loaded and checked your keymap.

It seem you have the shortcut mapped multiple times !  
Search `animation.time_scrub` and delete all wrong shortcut before saving preferences to leave only the one corresponding to your need.

![image](https://user-images.githubusercontent.com/7763187/163875842-91ceb3d0-f494-4ec2-aa4c-fb8efadf40fb.png)

Don't know how it happened...
I don't see any duplicate on my own config.

Did you export and re-import your keymap config file at some point ?

Anyway, do as stated above, save your prefs, restart blender and it should be ok.

If you delete all the keymaps accidentally, just deactivate and reactivate the addon (so it register a new one).

cheers
Samuel

**Comment by gakutada** [comment] 2022-04-18 21:59
Sweet, thank you Samuel!

Yes, that seems to be working.
I have no idea where those duplications happened and I checked google but I
could not find the solution yet.

Thank you for looking into it. I love the brush and tools so much!
cheers
Gaku
  ____

 *VEDA* online ltd http://veda-online.com/  wellington NZ
http://gakutada.com/

**Comment by Pullusb** [comment] 2022-04-19 20:34
Cool!
Marking this as resolved since I don't see how to reproduce for now.

You have [Daniel Martinez Lara](https://twitter.com/_pepeland_) to thank for the Brushes, I just did the code to download his brush pack (along with all the other tools of course 😉)

Since you used GP for a while and in a specific way I'm interested in your feedback, even if I have absolutely no time currently to add any features ^^ !
Is there any tool lacking in your use or something you'd like to have in GP ?

If you have any ideas or suggestions in that regard, feel free to open an _improvement idea_ issue.

**Closed by Pullusb** 2022-04-19 20:34 UTC
